### ISSUE TITLE
프로젝트 바로 실행하면 람다 함수내에서 serverless-nuxt 패키지를 찾지못합니다.

### ISSUE THREAD

**Issue by yoonjaepark** [wan2land/aws-cdk-samples#1]
람다 함수내에 모듈이 없어서그런거같은데 어떻게 해결하면될까요?
Cannot find module 'serverless-nuxt'

**Comment by wan2land** [comment]
`sample-nuxt-app`를 실행하신걸로 판단되는데, `npm install serverless-nuxt`를 해도 해결되지 않던가요..?
좀 더 자세한 상황 설명 부탁드립니다.

**Comment by yoonjaepark** [comment]
네! sample-nuxt-app 를 클론해서 .envrc 파일 aws 키값들 변경후 infra/nuxt-stack.ts 파일에서 도메인 관련 내용만 주석 후

```javascript
import { EndpointType, LambdaRestApi } from '@aws-cdk/aws-apigateway'
import { Certificate } from '@aws-cdk/aws-certificatemanager'
import { Code, Function as LFunction, Runtime } from '@aws-cdk/aws-lambda'
import { Construct, Stack, StackProps } from '@aws-cdk/core'
import { join } from 'path'

// const DOMAIN_NAME = 'sample.app'
// const CERTIFICATE_ARN = 'arn:aws:acm:us-east-1:~~~~'

export class NuxtStack extends Stack {
  public constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props)

    const code = Code.fromAsset(join(__dirname, '../dist'))

    new LambdaRestApi(this, 'SampleNuxt', {
      // domainName: {
      //   endpointType: EndpointType.EDGE,
      //   domainName: DOMAIN_NAME,
      //   certificate: Certificate.fromCertificateArn(this, 'Certificate', CERTIFICATE_ARN),
      // },
      handler: new LFunction(this, 'HomeHandler', {
        runtime: Runtime.NODEJS_12_X,
        code,
        handler: 'handler.render',
      }),
    })
  }
}

```


```
npm install
npx cdk bootstrap
npm run build && npm run deploy
```

배포했는데 에러 발생하는데 혹시 제가 뺴먹은게 있는지 도움부탁드립니다 ㅠ

--
 

<br class="Apple-interchange-newline">
<img width="1347" alt="스크린샷 2021-05-12 오전 12 33 35" src="https://user-images.githubusercontent.com/6939460/117843360-b6c52780-b2b9-11eb-81d9-483ac1fe772c.png">
<img width="1005" alt="스크린샷 2021-05-12 오전 12 34 44" src="https://user-images.githubusercontent.com/6939460/117843540-dd835e00-b2b9-11eb-879f-9254b02370f8.png">

**Comment by wan2land** [comment]
1.  에러로그를 보니 vue 가 없다고 나오네요. 로컬 워크스페이스에서 `npm ls --prod=true --parseable=true`  입력시, 람다로 배포될 패키지 목록이 출력되는데 여기에 vue가 포함되어있는지 확인 부탁드려요. (nuxt가 업데이트가 엄청 잦아서 의존도가 종종 깨지기도 합니다.) 만약 포함되어있지 않다면 package-lock 파일을 삭제하고 다시 인스톨을 시도해보세요.
2.  `dist` 디렉토리 내에 복사된 node\_modules 폴더에 vue가 포함되어있는지 확인해보세요.

람다쪽에서 뭔가 모듈을 찾을 수 없단 에러가 나오면 대부분, 1, 2번을 확인하면서 추적하면 해결 가능합니다. 예시코드 자체가 꽤 오래전에 작성된거라서 의존도가 제대로 해결이 안될 가능성이 농후합니다. ㅠㅠ..

참고로, Nuxt를 Lambda 위에 돌릴때는 CDK보다는 serverless를 사용하는게 더 쉽습니다. nuxt에 한해서는 저도 serverless를 사용하고 있습니다. ㅎㅎ;;  
([https://github.com/wan2land/serverless-nuxt](https://github.com/wan2land/serverless-nuxt) 이 라이브러리는 최신버전의 nuxt까지 대응되어있습니다.)

**Comment by yoonjaepark** [comment]
@wan2land 답변감사드립니다!

**Comment by wan2land** [comment]
@yoonjaepark 해당문제가 저한테도 재현되었네요. npm 버전이 7 이상인 경우, lockfileVersion: 2 인경우 해당 문제가 발생했었습니다.

distize에 관련 버그 패치가 이루어졌습니다. v2.1.1 이상 버전을 사용하시면 됩니다.
